# Site settings
name: Caesar Zhang
title: Caesar's Site
description: "Caesar Zhang's Site"
url:         "https://caesar73.github.io"
date_format: "%b %-d, %Y"
email: rayanddoctor@126.com
public_key_url: "https://raw.pastebin.com/LINK-TO-PUBLIC-KEY"
blog_url: "/blog"


# Optional features
animated:             false
show_related_posts:   false
show_post_footers:    false
show_social_icons:    false
ajaxify_contact_form: false
enable_mathjax: false
extended_fonts: false
enable_anchorjs: false


# Facebook Page integration
# (for instant articles and other stuff)
fb_page: false
fb_page_id:

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments:
facebook_appid:
facebook_comments_number: 10


# Social icons
github_username: Caesar73
bitbucket_username:
stackoverflow_id:
codepen_username: your_codepen_username_goes_here
facebook_username: your_facebook_username_goes_here
vk_username: your_vk_username_goes_here
twitter_username: your_twitter_username_goes_here
skype_username:
steam_nickname:
google_plus_id:
google_plus_username: your_google_plus_username_goes_here
linkedin_username: your_linked_in_username_goes_here
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:
vine_username:  your_vine_username_goes_here
instagram_username:  your_instagram_username_goes_here
flickr_username: your_flickr_username_goes_here
steam_username: your_steam_username_goes_here
soundcloud_username:  your_soundcloud_username_goes_here
stack_of_username: your_stack_overflow_account_id_number_goes_here
reddit_username: your_reddit_username_goes_here
medium_username:  your_medium_username_goes_here
tumblr_username: your_tumblr_username_goes_here
weibo_username: your_weibo_username_goes_here
lastfm_username: your_lastfm_username_goes_here


# Post sharing icons
show_sharing_icons: false
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  share_buttons:
    text:         'Share this post!'
    facebook:     'Share on Facebook'
    twitter:      'Share on Twitter'
    googleplus:   'Share on Google+'
    linkedin:     'Share on LinkedIn'
    digg:         'Share on Digg'
    tumblr:       'Share on Tumblr'
    reddit:       'Share on Reddit'
    stumbleupon:  'Share on StumbleUpon'
    hackernews:   'Share on Hacker News'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  index:
    coming_soon: 'Coming soon...'
  contact:
    email:    'Email Address'
    content:  'What would you like to say?'
    subject:  'New submission!'
    submit:   'Say Hello'
    ajax:
      sending:  'sending..'
      sent:     'Message sent!'
      error:    'Error!'
  thanks: 'Thanks for contacting us. We will reply as soon as possible.'
  og_locale: 'en_US'



avatar: yes
#avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
#avatar_img_path: "https://avatars2.githubusercontent.com/u/17301305"
avatar_img_path: "https://avatars1.githubusercontent.com/u/6374303"

front_img: yes
front_img_path: "imgs/background.jpg"

background_img_path: "imgs/index/bg.jpg"
overlay_svg_img_path: "imgs/index/overlay.svg"
overlay_png_img_path: "imgs/index/overlay-pattern.png"

#front_img_path: "https://external.url/image.jpg"


favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"



# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  style: compressed
gems:
  - jekyll-paginate
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor]

